# Jekyll
timezone: Asia/Tokyo
encoding: UTF-8

future: false
show_drafts: false

#relative_permalinks: true

permalink: /api/button/:slug:output_ext
#paginate_path: 'page:num'
exclude:
  # general repository files
  - README.md
  - CODE_OF_CONDUCT.md
  - CNAME
  # IntelliJ
  - .idea
  # Docker
  - docker-compose.yml
  - Dockerfile
  # Ruby
  - Gemfile
  - Gemfile.lock
  - vendor
  # Node.js
  - package.json
  - package-lock.json
  - node_modules
  - coverage
  - tsconfig.json
  - tslint.json

markdown: kramdown

kramdown:
  input: GFM

# Plugins
theme:

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Plugins Config
## common
title: さなボタン(2)
description: >-
  名取さなの声が再生されるボタン置き場。

# jekyll-github-metadata
repository: sanabutton/sanabutton.github.io
